name: Sync Version from SDK

on:
  repository_dispatch:
    types: [sdk-release]

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version from payload
        id: get_version
        run: echo "version=${{ github.event.client_payload.version }}" >> $GITHUB_OUTPUT

      - name: Update README.md
        run: |
          sed -i'' -E 's/(implementation\("com\.dream\.monet:ads:)[0-9a-zA-Z\.\-]+("\))/\1${{ steps.get_version.outputs.version }}\2/' README.md

      - name: Update gradle/libs.versions.toml
        run: |
          sed -i'' -E 's/(dream-monet-ads = ")[0-9a-zA-Z\.\-]+(")/\1${{ steps.get_version.outputs.version }}\2/' gradle/libs.versions.toml

      - name: Update CHANGELOG.md
        env:
          CHANGELOG_CONTENT: ${{ github.event.client_payload.changelog }}
        run: printf "%s" "$CHANGELOG_CONTENT" > CHANGELOG.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md gradle/libs.versions.toml CHANGELOG.md
          git commit -m "docs: Update SDK version to ${{ steps.get_version.outputs.version }} and sync CHANGELOG"
          git push

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          body: ${{ github.event.client_payload.changelog }}
          draft: false
          prerelease: false
